jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      - uses: actions/setup-node@v4
      # Ставим зависимости
      - run: make start
      # Запускаем линтер
      - run: make lint
      # Запускаем тесты
        run: make test 
